vrf-dns-helper: change FIB rule to match iif loopback
On some systems running switchdev with mlxsw, the driver forbids
installation of non-default FIB rules, except the ones with iif
of the loopback netdev:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=05414dd116c549a0b9dd57ee4e73ddd9a0038e41

Example:
root@mellanox:mgmt:~# /usr/lib/vrf/vrf-helper create mgmt 1001
Failed to add ip rule to 10.0.0.1 lookup 1001 prio 99
root@mellanox:mgmt:~# ip rule add to 10.0.0.1 lookup 1001 prio 99
Error: mlxsw_spectrum: FIB rules not supported.
root@mellanox:mgmt:~# ip rule add to 10.0.0.1 lookup 1001 prio 99 iif lo
root@mellanox:mgmt:~#

This patch fixes this issue by adding extra match for iif=loopback
device to indicate that the FIB rule does not have to be offloaded.

Signed-off-by: Alexander Petrovskiy <alexpe@nvidia.com>